### ISSUE TITLE
MVP WebGUI

### ISSUE THREAD

**Issue by ctengel** [ctengel/taskmaster#12]
Split from #4 (fully API based)

Just basic CRUD so this becomes usable for daily tasks...enhance with #11 later

**Comment by ctengel** [comment]
Note we basically have to make the same design decision as in ctengel/LPM-index#3

**Comment by ctengel** [comment]
- https://github.com/dsternlicht/RESTool
- https://netdevops.me/2019/creating-a-bootstrap-based-front-end-for-your-simple-rest-service/
- https://www.reddit.com/r/flask/comments/aic4vj/how_do_i_make_a_gui_for_my_rest_api/
- https://testdriven.io/blog/developing-a-single-page-app-with-flask-and-vuejs/

**Comment by ctengel** [comment]
- See notepad
- See wanderer idea
- see insomnia/postman

**Comment by ctengel** [comment]
we need two addition paths
- add a new task to today view (default unstaged)
- add unsorted task (maybe to any view???)

**Comment by ctengel** [comment]
- Also a way to view done tasks? - like #20 and/or #71 ?
- Way to complete a task AND schedule recurrence of it?
  - do a `POST /tasks/<id>/action` close&duplicate
  - distinct from #64 ? (or is this webgui implementation of that CLI version?) 
- Note that delete #46 is not in scope

**Comment by ctengel** [comment]
Seem to have figured out context issue for now ( see #86 )

However, new problem. WebGUI design envisions multiple execute contexts... i.e. one can stage tasks in one context, swap to another, and then swap back contexts.

API and CLI was not built with this in mind, they were built with single "stage" of all contexts.

So if we are in GUI "execute mode" we cannot pull just one context - `GET /tasks/?mode=execute&context=xyz` fails.

Maybe this IS an issue for #86 - decide how this should work.

**Comment by ctengel** [comment]
Per #86 discussion - conform to API for now - single stage.

**Comment by ctengel** [comment]
still todo

- [ ] initial context picker
- [ ] bulk unstage (see  #11 )
- [ ] any concept of priority (see #45 )
- [ ] implement task actions
- [ ] stage mode (see #87 )
- [ ] add tasks

**Comment by ctengel** [comment]
1. Actions
2. Manually add timelines and adjust contexts via CLI
3. Start eating the dog food
4. Test and fix stage mode
5. Prioritize
6. Other

**Comment by ctengel** [comment]
Quality of life:

- context picker
- if task is different context, link to switch
- after doing an action maintain stage/exec mode

**Comment by ctengel** [comment]
- table mode
- change context?
- change due date

**Comment by ctengel** [comment]
make available on mobile

**Comment by ctengel** [comment]
https://stackoverflow.com/questions/9117209/no-line-break-between-button-and-form

**Comment by ctengel** [comment]
essentially done, see "Restful wander ideas" in keep
